// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwizutvbwaiskqwfycnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53aXp1dHZid2Fpc2txd2Z5Y25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODQ2MjIsImV4cCI6MjA2ODU2MDYyMn0.CN9sfGx5CNDTWNPe_mmPqQ3HkQJZO6-9De8rTfx1XSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});